swagger: '2.0'

info:
  version: "5.0.0"
  title: Gluu casa admin API
  description: Allows to configure Casa programmatically
  license:
    name: Gluu Casa
    url: https://gluu.org/docs/casa/#license

#Demo server host
host: test-casa.gluu.org

basePath: /casa/rest
schemes:
 - https

consumes:
  - application/json
produces:
  - application/json

paths:

  /authn-methods:
    get:
      description: Returns the authentication methods currently enabled for Casa

      responses:
        200:
          description: Successful response. A JSON array is returned. Every method is
            identified by an acr String
        500:
          description: There was a failure executing the operation

  /authn-methods/disable:
    post:
      description: Disables a specific authentication method
      
      parameters:
        -
          name: acr
          in: query
          description: Identifier of the authentication method to disable
          required: true
          type: string
          
      responses:
        200:
          description: Successful response. Empty body
        404:
          description: acr is not known or method is not found in the list of enabled methods. Empty body
        500:
          description: There was a failure executing the operation

  /authn-methods/assign-plugin:
    post:
      description: Assigns the responsible plugin for a given authentication method (in terms of enrollment).
        Responsibility can also be delegated to an internal (default) plugin implementation if available for
        the method in question
      
      parameters:
        -
          name: acr
          in: query
          description: Identifier of the authentication method
          required: true
          type: string
        -
          name: plugin
          in: query
          description: Identifier of the plugin to assign. If this param is missing or empty, the default
            implementation is assigned (if existing) 
          required: false
          type: string
          
      responses:
        200:
          description: Successful response. Empty body
        400:
          description: Inconsistent parameters, eg. acr is missing/empty, the plugin does not actully implement
            the method designated by the acr, the custom script corresponding to the acr is not enabled.
        500:
          description: There was a failure executing the operation
          